test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('url_parser.urls')),
    path('admin/', admin.site.urls),
]

url_parser/urls.py
from django.urls import path
from .views import index


urlpatterns = [
    path('index', index),
]

url_parser/models.py
from datetime import datetime
from django.db import models
from .server import ParsingServer


# Записи о запросах
# Во время сохранения передает запрос на сервер запросов, который сохраняет запрос в очередь
class RequestUrl(models.Model):
    url = models.URLField(blank=False, null=False)
    time_to_request = models.DateTimeField(blank=True, default=datetime.now)

    def save(self, *args, **kwargs):
        if self.time_to_request is None:
            self.time_to_request = datetime.now()


        super(RequestUrl, self).save(*args, **kwargs)
        ParsingServer.get_instance().add_to_server(self)

    def __str__(self):
        return self.url


# Записи о выполенных запросах
class ResponseUrl(models.Model):
    STATUS_ERROR = 'er'
    STATUS_OK = 'ok'

    RESPONSE_STATUS_CHOICES = [
        (STATUS_OK, 'OK'),
        (STATUS_ERROR, 'ERROR'),
    ]

    request_url = models.OneToOneField(RequestUrl, on_delete=models.CASCADE)
    response_status = models.CharField(max_length=2, choices=RESPONSE_STATUS_CHOICES, default=STATUS_ERROR)
    title = models.CharField(max_length=255, blank=True, null=True)
    encoding = models.CharField(max_length=15, blank=True, null=True)
    h1 = models.CharField(max_length=255, blank=True, null=True)

    def response_content(self):
        content = [
            self.title,
            self.encoding,
            self.h1
        ]

        return ', '.join(filter(None, content))

    def has_content(self):
        return bool(self.response_content())

    def __str__(self):
        return self.request_url.url


# Записи очереди для сервера запросов
# Используется сервером запросов для сохранения данных очереди
# для возобновления работы после остановки приложения
class ParsingServerQueue(models.Model):
    request_url = models.OneToOneField(RequestUrl, on_delete=models.CASCADE)

url_parser/views.py
from django.shortcuts import render
from .models import ResponseUrl, RequestUrl


def index(request):
    responses = ResponseUrl.objects.all().prefetch_related()

    return render(request, 'url_parser/index.html', {'responses': responses})

url_parser/templates/url_parser/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Тестовый проект</title>
    <style>
        textarea {
            resize: none;
        }
    </style>
</head>
<body>
<textarea id="request-status" cols="80" rows="30" readonly>{% for response_item in responses %}&lt;{{ response_item.request_url.time_to_request|date:"d.m.Y H:i:s" }}&gt;: {{ response_item.get_response_status_display }}
{% endfor %}</textarea>
<textarea id="response-status" cols="80" rows="30" readonly>{% for response_item in responses %}{{ response_item.request_url.url }}{% if response_item.has_content  %} - {{ response_item.response_content }}{% endif %}
{% endfor %}</textarea>
</body>
</html>